name: quiz_test
description: quiz.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  flutter_bloc: 8.0.1
  go_router: 4.2.6
  dio: 4.0.6
  get_it: 7.2.0
  json_annotation: 4.6.0
  freezed_annotation: 2.1.0
  lottie: ^1.4.1

  injectable: 1.5.3
  logger: 1.1.0
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^3.4.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: 2.0.3+1
  json_serializable: 6.3.1
  build_runner: 2.1.11
  injectable_generator: 1.5.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

